#!/bin/sh
###BEGIN INIT INFO########################
#
# start-stop-status
# Starts, stops the CCU-Historian server and
# reports status to the package manager
#
###END INIT INFO##########################

source /etc/profile

PID=""
DIR="/var/packages/ccu-historian/target"
cd "$DIR"

get_pid () 
{
   #use "-f 1"
   PID=`ps |grep java |grep ccu-historian.jar |cut -d " " -f 1`
   
   #if PID is <10000 than "-f 1" is empty so use "-f 2"
   if [ -z $PID ]; then
      PID=`ps |grep java |grep ccu-historian.jar |cut -d " " -f 2`
   fi
}


case $1 in
  start)
    java -jar ccu-historian.jar > ccu-historian.log 2>&1 &
    exit $?
  ;;
  stop)
    get_pid
    kill $PID 
    exit $?
  ;;
  status)

     get_pid
     if [ -z  $PID ]; then
	  # is not running
		exit 1
	  else
	  # is running
	exit 0
      fi   

  ;;
  log)
    echo "$DIR/ccu-historian.log";
    exit 0
  ;;
  *)
    exit 0
  ;;
esac
